os:
  - linux
  - osx

sudo: false

language: c

before_install:
  - pip install --user cpp-coveralls

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update > /dev/null; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew reinstall libtool > /dev/null; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install openssl libidn rtmpdump libssh2 c-ares libmetalink libressl nghttp2; fi

before_script:
  - ./buildconf

script:
  - ./configure --disable-shared --enable-debug --enable-maintainer-mode --enable-code-coverage && make -sj && make TFLAGS=-n test-nonflaky

compiler:
  - clang
  - gcc

notifications:
  email: false

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
